# https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions
name: "goldenwere-actions/surge"
author: "Benjamin Arthur Lupton <b@lupton.cc> & Goldenwere <contactgoldenwere@gmail.com"
description: "GitHub Action to publish your project to https://surge.sh"
branding:
  icon: "anchor"
  color: "green"

# https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions#inputs
inputs:
  surgeLogin:
    description: "Your Surge email/username, get it via the `surge whoami` command."
    required: true
  surgeToken:
    description: "The token to authorize the deployments to Surge, get via the `surge token` command."
    required: true
  surgeProject:
    description: "The path that you want to deploy to Surge."
    default: "."
    required: false
  surgeURL:
    description: "The URL (full root) to deploy to Surge."
    required: true

# https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-run-steps-actions
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/action.bash
      shell: bash
      env:
        SURGE_LOGIN: ${{inputs.surgeLogin}}
        SURGE_TOKEN: ${{inputs.surgeToken}}
        SURGE_PROJECT: ${{inputs.surgeProject}}
        SURGE_URL: ${{inputs.surgeURL}}